#Use the new container-based infrastructure
sudo: false

#Install some apt packages needed for spcomp
addons:
    apt_packages:
        - lib32z1
        - lib32stdc++6

language: c
#Set the build environment
env:
  global:
    - INCLUDE=addons/sourcemod/scripting/include
    - SCRIPTING=addons/sourcemod/scripting
    - PLUGINS=addons/sourcemod/plugins
  matrix:
    - SMVERSION=1.8
    - SMVERSION=1.9
install:
    # Sourcemod download
    - wget --input-file=http://sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux
    - tar -xzf $(cat sourcemod-latest-linux)
before_script:
    - chmod +x $SCRIPTING/spcomp
    - mkdir $SCRIPTING/compiled
script: $SCRIPTING/spcomp -E -o$SCRIPTING'/compiled/shop' -v0 $SCRIPTING'/shop.sp'

#Release
before_deploy:
    - mkdir shop shop/cfg shop/cfg/shop shop/addons shop/addons/sourcemod shop/addons/sourcemod/plugins shop/addons/sourcemod/scripting shop/addons/sourcemod/scripting/include shop/addons/sourcemod/translations shop/addons/sourcemod/configs
    - mv $SCRIPTING/shop.sp shop/$SCRIPTING
    - mv $SCRIPTING/shop shop/$SCRIPTING
    - mv $SCRIPTING/compiled/* shop/$PLUGINS
    - mv $INCLUDE/shop* shop/$INCLUDE
    - rsync -a --prune-empty-dirs --include '*/' --include 'shop*' --exclude '*' addons/sourcemod/translations/ shop/addons/sourcemod/translations/
    - mv addons/sourcemod/configs/shop* shop/addons/sourcemod/configs
    - mv cfg/shop/* shop/cfg/shop
    - mv LICENSE shop
    - zip -rq shop shop
    - tar -czf shop.tar.gz shop
deploy:
    provider: releases
    api_key: ${GH_TOKEN}
    file:
         - shop.zip
         - shop.tar.gz
    skip_cleanup: true
    on:
       tags: true
#Notifications
notifications:
    email: false